### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by takeshi4126** [takeshi4126/mhews#4]
The following error has been reported from quite a number of Android devices.

android.content.res.Resources$NotFoundException: 
  at android.content.res.Resources.getValue (Resources.java:2558)
  at android.content.res.Resources.getDrawable (Resources.java:2001)
  at android.content.res.Resources.getDrawable (Resources.java:1987)
  at android.content.res.Resources.getDrawable (Resources.java:1961)
  at org.apache.cordova.splashscreen.SplashScreen.onConfigurationChanged (SplashScreen.java:210)
  at org.apache.cordova.PluginManager.onConfigurationChanged (PluginManager.java:509)
  at org.apache.cordova.CordovaActivity.onConfigurationChanged (CordovaActivity.java:492)
  at android.app.ActivityThread.performConfigurationChanged (ActivityThread.java:5515)
  at android.app.ActivityThread.handleConfigurationChanged (ActivityThread.java:5711)
  at android.app.ActivityThread.handleConfigurationChanged (ActivityThread.java:5569)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1917)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7224)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

The problem exists in 1.2.3 (latest release) and 1.2.5 (only released as beta version.)

**Comment by takeshi4126** [comment]
It seems the same issue as [this one](https://github.com/Minds/mobile/issues/18). Recreated with my Sony Experia Z2, by rotating the screen while the splashscreen is displayed:

E/AndroidRuntime(  725): FATAL EXCEPTION: main
E/AndroidRuntime(  725): Process: ws.gov.samet.mhews, PID: 725
E/AndroidRuntime(  725): android.content.res.Resources$NotFoundException: Resource ID #0x7f020019
E/AndroidRuntime(  725): 	at android.content.res.Resources.getValue(Resources.java:1131)
E/AndroidRuntime(  725): 	at android.content.res.Resources.getDrawable(Resources.java:706)
E/AndroidRuntime(  725): 	at org.apache.cordova.splashscreen.SplashScreen.onConfigurationChanged(SplashScreen.java:210)
E/AndroidRuntime(  725): 	at org.apache.cordova.PluginManager.onConfigurationChanged(PluginManager.java:509)
E/AndroidRuntime(  725): 	at org.apache.cordova.CordovaActivity.onConfigurationChanged(CordovaActivity.java:492)
E/AndroidRuntime(  725): 	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3949)
E/AndroidRuntime(  725): 	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4025)
E/AndroidRuntime(  725): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
E/AndroidRuntime(  725): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  725): 	at android.os.Looper.loop(Looper.java:212)
E/AndroidRuntime(  725): 	at android.app.ActivityThread.main(ActivityThread.java:5151)
E/AndroidRuntime(  725): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  725): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(  725): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime(  725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
E/AndroidRuntime(  725): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by takeshi4126** [comment]
PR #7 was issued.
